# Vist https://cloud.google.com/appengine/docs/python/config/appconfig
# for more information on the app.yaml file

# The Project ID of the application we created at
# https://console.developers.google.com/project
application: mjm-gae-tutorial
version: step-two
runtime: python27
api_version: 1
threadsafe: true

# The GAE SDK comes with a bunch of libraries you can use out of the box
# All you have to do is tell it what libraries you are wanting to use.
# For a full list of available python libraries visit:
# https://cloud.google.com/appengine/docs/python/tools/libraries27
libraries:
- name: webapp2
  version: latest

handlers:
- url: /.*
  script: main.app
